version: '3.8'

services:
  db:
    container_name: springdatarest-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'madb'
      MYSQL_USER: 'safouat'
      MYSQL_PASSWORD: '111'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - springdatarest-db-data:/var/lib/mysql
    ports:
      - "3306:3306"  # Expose MySQL port to the host machine
    networks:
      - app_network

  server:
    image: myimage22
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/madb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: safouat
      SPRING_DATASOURCE_PASSWORD: '111'
      SPRING_APPLICATION_NAME: SpringDataRest
      SERVER_PORT: 9093
    ports:
      - "9093:9093"  # Expose Spring Boot server port to the host machine
    networks:
      - app_network

  front:
    image: frontend
    depends_on:
      - server
    ports:
      - "3000:3000"  # Expose the frontend on port 8080
    networks:
      - app_network

volumes:
  springdatarest-db-data:
    driver: local

networks:
  app_network:
    driver: bridge
