version: '3.3'
services:
  db:
    container_name: pain-care-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'PainCare'
      MYSQL_USER: 'safouat'
      MYSQL_PASSWORD: '111'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '30001:3306'
    volumes:
      - pain-care-db:/var/lib/mysql
      - ./src/main/java/Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Mount the schema file here
  server:
    container_name: pain-care-server
    restart: always
    ports:
      - 8002:8080
    build:
      context: .
    volumes:
      - /app/webcontent/assets/avatars
      - /app/webcontent/assets/blogs-images
    depends_on:
      - db
volumes:
  pain-care-db:

